name: Release BwKeySync

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: '1.23'
          goos: 'linux'
          goarch: 'amd64'
          ldflags: '-extldflags=-lm'
          binary_name: "BwKeySync-linux-amd64"

  release-linux-arm64:
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM64 build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu musl-tools

      - name: Build release
        run: |
          export CC=aarch64-linux-gnu-gcc
          export CGO_ENABLED=1
          export CGO_CFLAGS="-g -O2"
          go build -v -ldflags '-extldflags=-lm' -o BwKeySync .

      - name: Package release
        run: |
          mkdir -p release
          tar -czvf "release/BwKeySync-${GOOS}-${GOARCH}.tar.gz" BwKeySync
          md5sum "release/BwKeySync-${GOOS}-${GOARCH}.tar.gz" > "release/BwKeySync-${GOOS}-${GOARCH}.tar.gz.md5"

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/BwKeySync-${{ env.GOOS }}-${{ env.GOARCH }}.tar.gz
            release/BwKeySync-${{ env.GOOS }}-${{ env.GOARCH }}.tar.gz.md5
