name: Release BwKeySync

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: '1.23'
          goos: 'linux'
          goarch: 'amd64'
          ldflags: '-extldflags=-lm'

  release-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM64 build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: '1.23'
          goos: 'linux'
          goarch: 'arm64'
          ldflags: '-extldflags=-lm'
          pre_command: 'export CC=aarch64-linux-gnu-gcc CGO_ENABLED=1'
